$(info #####################IMPORTANT!############################# \\
you must have a terraform.tfvars file with the actual values! \
#####################IMPORTANT!############################# \
\
This is an additional line of the warning message. \
You can add more lines by using the '\' character at the end of each line.)